version: '3'
services:
  api:
    container_name: dev_api
    build: 
      ./api
    ports:
        - "5000:5000"
    environment: 
        - PGUSER=user
        - PGHOST=db
        - PGPASSWORD=password
        - PGDATABASE=myDb
        - PGPORT=5432
    volumes:
        - type: bind
          source: ./api
          target: /code
    depends_on:
        - db
  db:
    image: postgres:12.4
    container_name: dev_db
    volumes:
      - "dev_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=myDb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  dev_db:
   
