version: '3'
services:
  api:
    build: 
      ./api
    ports:
        - "5000:5000"
    volumes:
        - type: bind
          source: ./api
          target: /code
    depends_on:
        - db
  db:
    image: postgres:12.4
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=myDb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
   