version: '3'
services:
  api:
    container_name: test_api
    build: 
      ./api
    ports:
        - "5000:5000"
    environment: 
        - ENV=test
        - PGUSER=user
        - PGHOST=db
        - PGPASSWORD=password
        - PGDATABASE=testDb
        - PGPORT=5432
    volumes:
        - type: bind
          source: ./api
          target: /code
    depends_on:
        - db
  db:
    image: postgres:12.4
    container_name: test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=testDb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  test_db:
   
