version: '3'
services:
  socket:
    build: 
      ./socket
    ports:
        - "3000:3000"
    volumes:
        - type: bind
          source: ./socket
          target: /code
    depends_on:
        - api
  api:
    build: 
      ./api
    ports:
        - "5000:5000"
    environment: 
        - PGUSER=user
        - PGHOST=db
        - PGPASSWORD=password
        - PGDATABASE=myDb
        - PGPORT=5432
    volumes:
        - type: bind
          source: ./api
          target: /code
    depends_on:
        - db
  db:
    image: postgres:12.4
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=myDb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
   